brew "maven"
brew "git"
brew "git-lfs"
brew "nodenv"
brew "jenv"
brew "nodenv"
brew "pipenv"
brew "python@3.10"
brew "ansible"
brew "terraform"
brew "awscli"

cask "firefox"
cask "temurin"
cask "postman"
cask "wireshark"
cask "staruml"
cask "camunda-modeler"
cask "jetbrains-toolbox"
cask "visual-studio-code"
cask "camunda-modeler"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "docker"
cask "ngrok"

mas "Xcode", id: 497799835
